truncate table almacen_almacenes
truncate table almacen_tipos
truncate table asesoria_juridica_medio
truncate table asesoria_juridica_procedencia
truncate table asesoria_tipo_asuntos 
truncate table altas_bajas_situaciones
truncate table bt_idiomas
truncate table bt_nivel
truncate table bt_tipo_bolsa 
truncate table bt_demandas_tipo
truncate table cabeceras
truncate table caja_pagos
truncate table caja_salidas
truncate table cartas
truncate table csi_facturas_emitidas
truncate table csi_lineas_fact_emitidas
truncate table csi_traspasos_basicos
truncate table csi_cobros
truncate table csi_cobros_multiples
truncate table domiciliaciones
truncate table remesas
truncate table fases
truncate table fases_informes
truncate table fases_colegiados
truncate table fases_clientes
truncate table fases_usos
truncate table fases_estados
truncate table fases_minutas
truncate table fases_liquidaciones
truncate table fases_otros_datos
truncate table fases_renuncias
truncate table fases_finales
truncate table fases_arquitectos
truncate table premaat_liquidaciones
truncate table expedientes
truncate table c_geograficos
truncate table cabecera 
truncate table callejero 
truncate table cargos 
truncate table cierre 
truncate table cip_tablas 
truncate table cip_tarifa 
truncate table cip_tipo_act 
truncate table ciudades 
truncate table coaatll_dip 
truncate table coaatmca_coef_b 
truncate table coaatmca_coef_c 
truncate table coaatmca_coeficientes 
truncate table coaatmca_dv 
truncate table coaatmca_tipologia_edif 
truncate table coef_ipc 
truncate table colegios 
truncate table colegios_matriculas 
truncate table colindantes 
truncate table colores  
truncate table comunidad_autonoma 
truncate table conceptos_domiciliables
truncate table conceptos_remesable
truncate table configura_campos 
truncate table configura_insercion 
truncate table consultas 
truncate table consultas_datos 
truncate table contadores 
truncate table csd_conexion_bd 
truncate table csd_seg_ip 
truncate table csd_seg_ip_exclusion 
truncate table csd_seg_tipo_idioma 
truncate table csd_sms 
truncate table csd_sms_bd_perfil 
truncate table csd_sms_campanya 
truncate table csd_sms_campos 
truncate table csd_sms_grupos 
truncate table csd_sms_grupos_detalle 
truncate table csd_sms_predefinidos 
truncate table csd_sms_programado 
truncate table csi_aeat_periodo 
truncate table csi_aeat_registro_contador 
truncate table csi_aeat_t_libro_iva 
truncate table csi_art_serv_correspo 
truncate table csi_articulos_servicios 
truncate table csi_asientos_predefinidos 
truncate table csi_balances 
truncate table csi_balances_a_p_balance 
truncate table csi_balances_cuentas_especial 
truncate table csi_balances_etcpn_columnas 
truncate table csi_balances_fun_especial 
truncate table csi_balances_pyg_mes 
truncate table csi_balances_t_balance 
truncate table csi_bancos 
truncate table csi_bancos_maestro 
truncate table csi_centros 
truncate table csi_centros_intragrupo 
truncate table csi_claves_retencion 
truncate table csi_columnas_importe 
truncate table csi_control_ejercicios 
truncate table csi_datos_economicos_anyo 
truncate table csi_diarios_parametrizaciones 
truncate table csi_ejercicios_abiertos 
truncate table csi_elems_inmov_grupo 
truncate table csi_elems_inmov_tipo_baja 
truncate table csi_elems_inmov_tipo_natura 
truncate table csi_elems_inmov_ubicacion 
truncate table csi_empresas 
truncate table csi_equiv_copia_empresa 
truncate table csi_fact_reclamaciones_tipos 
truncate table csi_familias 
truncate table csi_formas_de_pago 
truncate table csi_formas_de_pago_correspo 
truncate table csi_formulas_asientos_prede 
truncate table csi_lineas_asientos_prede 
truncate table csi_meses 
truncate table csi_npgc_tablas_modif 
truncate table csi_param_facturas 
truncate table csi_param_sigescon 
truncate table csi_proforma_a_factura
truncate table csi_proyectos 
truncate table csi_relacion_cuentas_npgc 
truncate table csi_series 
truncate table csi_t_aprobacion 
truncate table csi_t_asientos 
truncate table csi_t_asientos_predefinidos 
truncate table csi_t_conciliacion 
truncate table csi_t_destinatario_347 
truncate table csi_t_documento 
truncate table csi_t_estado_pago 
truncate table csi_t_evaluacion 
truncate table csi_t_iva 
truncate table csi_tipo_presupuesto 
truncate table csi_trimestres 
truncate table cuentas 
truncate table cuentas_pyme 
truncate table delegaciones 
truncate table domicilios
truncate table demarcaciones 
truncate table departamentos 
truncate table desc_gui_coefs 
truncate table desc_gui_pem 
truncate table desc_gui_tipo_act 
truncate table descuentos_visared 
truncate table devoluciones_motivos 
truncate table domiciliaciones_formatos 
truncate table dv_sobre_pem 
truncate table dv_tipo_act 
truncate table equivalencias 
truncate table escuela 
truncate table est_tipo_act 
truncate table est_tipo_act_tipo_obra_f 
truncate table est_tipo_obra 
truncate table expedientes_estado 
truncate table fases_admin_jud_tipos_rec 
truncate table fases_finales_acciones_realiza 
truncate table fases_incompatibilidades 
truncate table fases_renuncias_desglose 
truncate table formacion_areas_materias 
truncate table formacion_estados 
truncate table formacion_mant_test 
truncate table formacion_subtipo_conv 
truncate table formacion_test 
truncate table formacion_titulacion 
truncate table gcw_archivo 
truncate table gcw_aviso 
truncate table gcw_colegio 
truncate table gcw_modulo 
truncate table gcw_perfil 
truncate table gcw_preferencia 
truncate table gcw_registro 
truncate table gcw_registro_perfil 
truncate table gcw_tipo_archivo 
truncate table gcw_usuario 
truncate table gcw_usuario_perfil 
truncate table grupos 
truncate table ho_contenidos 
truncate table ho_parametros 
truncate table ho_tablas 
truncate table ho_tarifas 
truncate table ho_tarifas_contenidos 
truncate table hon_tablas 
truncate table honos_tablas_gui 
truncate table honos_tarifa_gui 
truncate table incidencias_expedientes 
truncate table incidencias_familias 
truncate table libros_ubicaciones 
truncate table listados 
truncate table menu 
truncate table meses 
truncate table messages 
truncate table messages_ca 
truncate table modalidades 
truncate table municipios 
truncate table musaat_asistencia 
truncate table musaat_cias_aseguradoras 
truncate table musaat_cober_exceso 
truncate table musaat_cober_peritos 
truncate table musaat_cober_src 
truncate table musaat_cober_tasadores 
truncate table musaat_coef_c 
truncate table musaat_coef_col 
truncate table musaat_coef_g 
truncate table musaat_coef_k 
truncate table musaat_desc_porc_part 
truncate table musaat_params_linea_fe
truncate table musaat_histo_cober_src
truncate table musaat_movimientos
truncate table musaat_src_estado 
truncate table musaat_src_t_poliza 
truncate table musaat_tarifa_e 
truncate table musaat_tarifas 
truncate table musaat_tipo_visado 
truncate table musaat_tipologia 
truncate table musaat_tipos_oo 
truncate table modificaciones
truncate table notificaciones 
truncate table origen_inhabilitacion 
truncate table otros_conceptos 
truncate table paises 
truncate table personalidad_juridica 
truncate table plantillas 
truncate table plantillas_campos 
truncate table plantillas_campos_extra 
truncate table poblaciones 
truncate table poblaciones_zonas 
truncate table premaat_grupo 
truncate table premaat_parentesco 
truncate table premaat_situacion 
truncate table premaat_tablas 
truncate table premaat_tipo_mut 
truncate table premaat_tipo_pres 
truncate table provincias 
truncate table registro_series 
truncate table registro_t_comunicado 
truncate table regsoc_tipo_entrada_agenda 
truncate table regsoc_tipo_forma_juridica 
truncate table regsoc_tipo_registro_mercantil 
truncate table regsoc_tipo_sancion 
truncate table sini_damnificados 
truncate table sini_estimacion_economica 
truncate table sini_tipo_danyos 
truncate table sini_tipo_estado_obra 
truncate table sini_tipo_reclamacion 
truncate table t_agrupaciones 
truncate table t_altas_bajas_situaciones 
truncate table t_aplicacion 
truncate table t_control_eventos 
truncate table t_descripcion_fases 
truncate table t_destinos 
truncate table t_documentos 
truncate table t_domicilios 
truncate table t_fases 
truncate table t_fases_finales 
truncate table t_gestion 
truncate table t_grupo 
truncate table t_grupo_permisos 
truncate table t_incompatibilidad 
truncate table t_informes 
truncate table t_laboratorio 
truncate table t_mensaje 
truncate table t_orientaciones_profesionales 
truncate table t_preguntas 
truncate table t_promotor 
truncate table t_promotor_grupos 
truncate table t_reparos_fases 
truncate table t_sello  
truncate table t_sello_posiciones 
truncate table t_sello_textos 
truncate table t_situaciones_profesionales 
truncate table t_tercero 
truncate table t_tramite 
truncate table t_transporte_comunicados 
truncate table t_traspaso_iva 
truncate table t_usos 
truncate table tarifas_coeficientes 
truncate table tarifas_importes 
truncate table tarifas_informes_x_tramite 
truncate table tarifas_superficie 
truncate table tarifas_tipo_act 
truncate table tarifas_tipo_obra 
truncate table tipo_act_familia 
truncate table tipo_cargo 
truncate table tipo_fases 
truncate table tipo_inhabilitacion
truncate table tipo_registro
truncate table tipos_envio_visared
truncate table tipos_facturas
truncate table tipos_honorarios
truncate table tipos_trabajos 
truncate table tipos_via
truncate table titulaciones
truncate table trabajos 
truncate table tratamientos
truncate table var_globales
truncate table web_ayuda
truncate table web_colegiados
truncate table web_estilos 
truncate table web_paginas 
truncate table web_plantillas  
go
