copy C:\ondevio_projects\sicap_trunk\lib\dlls\*.dll %2
copy C:\ondevio_projects\sicap_trunk\lib\obj_bancario\*.pbd %2
copy C:\ondevio_projects\sicap_trunk\lib\obj_bancario\sepaportservice.dll %2
copy C:\ondevio_projects\sicap_trunk\lib\*.pbd %2
copy C:\ondevio_projects\sicap_trunk\lib\*.pbx %2
copy C:\ondevio_projects\sicap_trunk\lib\sica_port_service.exe %2
move %1A_APLIC\A_APLIC.pbd %2
move %1A_CSD\A_CSD.pbd %2
move %1A_CSD_FU\A_CSD_FU.pbd %2
move %1A_CSD_SE\A_CSD_SE.pbd %2
move %1A_MANTEN\A_MANTEN.pbd %2
move %1aacsd_gastos\aacsd_gastos.pbd %2
move %1aacsd_gastos_apa.pbd %2
move %1aacsd_idiomas.pbd %2
move %1aacsd_idiomas_aux\aacsd_idiomas_aux.pbd %2
move %1aacsd_gastos\aacsd_tarifas_gastos_apa.pbd %2
move %1actualizaciones\actualizaciones.pbd %2
move %1administrativa_judicial\administrativa_judicial.pbd %2
move %1almacen\almacen.pbd %2
move %1aparatos_tecnicos\aparatos_tecnicos.pbd %2
move %1arquitec\arquitec.pbd %2
move %1arte_cemento\arte_cemento.pbd %2
move %1asesoria_juridica\asesoria_juridica.pbd %2
move %1asistente\asistente.pbd %2
move %1bt\bt.pbd %2
move %1c_evento\c_evento.pbd %2
move %1caja\caja.pbd %2
move %1caja_salidas\caja_salidas.pbd %2
move %1CIP\CIP.pbd %2
move %1CLIENTES\CLIENTES.pbd %2
move %1coaatg_honos\coaatg_honos.pbd %2
move %1cobros\cobros.pbd %2
move %1colegia\colegia.pbd %2
move %1consejo\consejo.pbd %2
move %1CONTA\CONTA.pbd %2
move %1cuotas\cuotas.pbd %2
move %1cursos_jornadas\cursos_jornadas.pbd %2
move %1domic\domic.pbd %2
move %1eimporta\eimporta.pbd %2
move %1eimporta_compartido\eimporta_compartido.pbd %2
move %1email\email.pbd %2
move %1escaner\escaner.pbd %2
move %1EXPE\EXPE.pbd %2
move %1factu_e\factu_e.pbd %2
move %1factu_fa\factu_fa.pbd %2
move %1fases\fases.pbd %2
move %1fasesmas\fasesmas.pbd %2
move %1final_obra\final_obra.pbd %2
move %1frontend\frontend.pbd %2
move %1fomento\fomento.pbd %2
move %1garantias\garantias.pbd %2
move %1gastos_pb.pbd %2
move %1GENERAL\GENERAL.pbd %2
move %1INCIDENC\INCIDENC.pbd %2
move %1ing_ret\ing_ret.pbd %2
move %1junta_gobierno\junta_gobierno.pbd %2
move %1LIBROS\LIBROS.pbd %2
move %1liquid\liquid.pbd %2
move %1listas\listas.pbd %2
move %1MENSAJES\MENSAJES.pbd %2
move %1MINUTAS\MINUTAS.pbd %2
move %1MUSAAT\MUSAAT.pbd %2
move %1PARAMETR\PARAMETR.pbd %2
move %1pbdom105.pbd %2
move %1pbwsclient105.pbd %2
move %1PFCAPSRV\PFCAPSRV.pbd %2
move %1PFCDWSRV\PFCDWSRV.pbd %2
move %1PFCMAIN\PFCMAIN.pbd %2
move %1PFCOLD\PFCOLD.pbd %2
move %1PFCUTIL\PFCUTIL.pbd %2
move %1PFCWNSRV\PFCWNSRV.pbd %2
move %1PFEAPSRV\PFEAPSRV.pbd %2
move %1PFEDWSRV\PFEDWSRV.pbd %2
move %1PFEMAIN\PFEMAIN.pbd %2
move %1PFEUTIL\PFEUTIL.pbd %2
move %1PFEWNSRV\PFEWNSRV.pbd %2
move %1plantillas\plantillas.pbd %2
move %1PREMAAT\PREMAAT.pbd %2
move %1proconta\proconta.pbd %2
move %1reclamaciones\reclamaciones.pbd %2
move %1reclamaciones_facturas\reclamaciones_facturas.pbd %2
move %1REG_ES\REG_ES.pbd %2
move %1regsoc\regsoc.pbd %2
move %1renuncias\renuncias.pbd %2
move %1REPAROS\REPAROS.pbd %2
move %1sellador\sellador.pbd %2
move %1sellador_compartido\sellador_compartido.pbd %2
move %1siniestros\siniestros.pbd %2
move %1z_coaatal\z_coaatal.pbd %2
move %1z_coaatavi\z_coaatavi.pbd %2
move %1z_coaatbi\z_coaatbi.pbd %2
move %1z_coaatbu\z_coaatbu.pbd %2
move %1z_coaatcc\z_coaatcc.pbd %2
move %1z_coaatcc_calculo_gastos\z_coaatcc_calculo_gastos.pbd %2
move %1z_coaatcu\z_coaatcu.pbd %2
move %1z_coaatgc\z_coaatgc.pbd %2
move %1z_coaatgu\z_coaatgu.pbd %2
move %1z_coaatgui\z_coaatgui.pbd %2
move %1z_coaatle\z_coaatle.pbd %2
move %1z_coaatll\z_coaatll.pbd %2
move %1z_coaatlr\z_coaatlr.pbd %2
move %1z_coaatmca\z_coaatmca.pbd %2
move %1z_coaatmu\z_coaatmu.pbd %2
move %1z_coaatna\z_coaatna.pbd %2
move %1z_coaatteb\z_coaatteb.pbd %2
move %1z_coaatter\z_coaatter.pbd %2
move %1z_coaattfe\z_coaattfe.pbd %2
move %1z_coaattg\z_coaattg.pbd %2
move %1z_coaatza\z_coaatza.pbd %2
move %1sica.exe %2


