declare @colegio varchar(10)
select @colegio = texto from var_globales where nombre = 'COLEGIO'
if @colegio = 'COAATMU'
begin
	insert into t_control_eventos(control,evento,activo,param1,param2,id_control) values ('INSERTA_BOTON','ABRIR_FASE','S','Plantillas','csd_plantillas','PLGEN')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_01','Renuncia DE. Comunicación a promotor','Renuncia DE. Comunicación a promotor.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_02','Renuncia DE. Comunicación a COA','Renuncia DE. Comunicación a COA.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_03','Renuncia DE. Comunicación a Ayuntamiento','Renuncia DE. Comunicación a Ayuntamiento.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_04','Renuncia CSS. Comunicación a promotor','Renuncia CSS. Comunicación a promotor.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_05','Renuncia CSS. Comunicación a Inspección Trabajo','Renuncia CSS. Comunicación a Inspección Trabajo.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_06','No ejecución obra. Comunicación a promotor','No ejecución obra. Comunicación a promotor.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_07','No ejecución obra. Comunicación a Inspección Trabajo','No ejecución obra. Comunicación a Inspección Trabajo.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_08','No ejecución obra. Comunicación a COA','No ejecución obra. Comunicación a COA.doc','FASES','S')
	insert into plantillas(codigo, descripcion, ruta, modulo, individual) values ('COAATMU_09','No ejecución obra. Comunicación a Ayuntamiento','No ejecución obra. Comunicación a Ayuntamiento.doc','FASES','S')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_01','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_01','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_01','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_01','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_01','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_02','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_02','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_02','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_02','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_02','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_03','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_03','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_03','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_03','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_03','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_04','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_04','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_04','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_04','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_04','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_05','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_05','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_05','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_05','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_05','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_06','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_06','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_06','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_06','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_06','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_07','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_07','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_07','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_07','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_07','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_08','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_08','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_08','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_08','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_08','campo5','Campo Extra 3')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_09','campo1','Nº Colegiado')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_09','campo2','CIF Promotor')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_09','campo3','Campo Extra 1')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_09','campo4','Campo Extra 2')
	INSERT INTO plantillas_campos (modulo,campo_formulario,campo_interno) VALUES ('COAATMU_09','campo5','Campo Extra 3')
end
;